export const Constant = {
    // Sprite Image
    Apple : "Apple",
    Arrow1_a : "Arrow1-a",
    Ballerina_a : "Ballerina-a",
    Balloon1_a : "Balloon1-a",
    Bananas : "Bananas",
    Basketball : "Basketball",
    Bell1 : "Bell1",
    Ben_a : "Ben-a",
    Bowl_a : "Bowl-a",
    Bear_a : "Bear-a",
    Bowtie : "Bowtie",
    Bread : "Bread",
    Broom : "Broom",
    Cake_a : "Cake-a",
    Casey_a : "Casey-a",
    CatFlying_a : "Cat Flying-a",
    Catcher_a : "Catcher-a",
    Chick_a : "Chick-a",
    CityBus_a : "City Bus-a",
    Cloud : "Cloud",
    Crab_a : "Crab-a",
    Crystal_b : "Crystal-b",
    Dinosaur1_a : "Dinosaur1-a",
    Dinosaur2_a : "Dinosaur2-a",
    Dinosaur3_a : "Dinosaur3-a",
    Dinosaur4_a : "Dinosaur4-a",
    Diver2 : "Diver2-a",
    Dog1_a : "Dog1-a",
    Dog2_c : "Dog2-c",
    Donut : "Donut",
    Dorian_a : "Dorian-a",
    Dove_a : "Dove-a",
    Dragon1_b : "Dragon1-b",
    Dragon_a : "Dragon-a",
    Glow_1 : "Glow-1",
    Gobo_a : "Gobo-a",
    Story_Z_3 : "story-Z-3",
    // Stage Image
    Jurassic : "Jurassic",
    // Sound
    Chill : "Chill",
    Rip : "Rip",
}
